

DROP TABLE IF EXISTS authentication_tokensdata;
  
CREATE TABLE authentication_tokensdata (
  USER_TOKEN VARCHAR NOT NULL,
  SERVICE_TOKEN VARCHAR NOT NULL,
  TRANSACTION_TOKEN VARCHAR  NOT NULL,
  USER_NAME VARCHAR NOT NULL,
  EXPIRES_IN INT NOT NULL,
  CREATE_DATE TIMESTAMP NOT NULL,
  API_KEY VARCHAR NOT NULL
  
);